"""'2210c744e893' - Blog tags."""

import sqlalchemy as sa

from alembic import op

#from lib.util_datetime import tzware_datetime
#from lib.util_sqlalchemy import AwareDateTime
"""
Blog tags

Revision ID: 2210c744e893
Revises: 05546c22ac6e
Create Date: 2016-11-01 13:13:16.323010
"""

# Revision identifiers, used by Alembic.
revision = '2210c744e893'
down_revision = '05546c22ac6e'
branch_labels = None
depends_on = None


def upgrade():
    """Command to migrate database forward."""

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tags',
        sa.Column(
            'id', sa.Integer(), nullable=False),
        sa.Column(
            'title', sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint('id'))
    op.add_column('posts', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'tags', ['tag_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    """Command to migrate database backwards."""

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'tag_id')
    op.drop_table('tags')
    ### end Alembic commands ###
