"""'18248a9ed8bb' - Page last modified."""

import sqlalchemy as sa

from alembic import op

from lib.util_datetime import tzware_datetime
from lib.util_sqlalchemy import AwareDateTime
"""
Page last modified

Revision ID: 18248a9ed8bb
Revises: 9583cbd0377a
Create Date: 2016-11-06 20:49:12.627465
"""

# Revision identifiers, used by Alembic.
revision = '18248a9ed8bb'
down_revision = '9583cbd0377a'
branch_labels = None
depends_on = None


def upgrade():
    """Command to migrate database forward."""

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pages_last_modified',
        sa.Column(
            'created_on', AwareDateTime(), nullable=True),
        sa.Column(
            'updated_on', AwareDateTime(), nullable=True),
        sa.Column(
            'id', sa.Integer(), nullable=False),
        sa.Column(
            'request', sa.Text(), nullable=False),
        sa.Column(
            'checksum', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'))
    ### end Alembic commands ###


def downgrade():
    """Command to migrate database backwards."""

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages_last_modified')
    ### end Alembic commands ###
