"""'216ce379d3f0' - Blog tags m2m."""

import sqlalchemy as sa

from alembic import op

#from lib.util_datetime import tzware_datetime
#from lib.util_sqlalchemy import AwareDateTime
"""
Blog tags m2m

Revision ID: 216ce379d3f0
Revises: 2210c744e893
Create Date: 2016-11-01 13:17:02.021376
"""

# Revision identifiers, used by Alembic.
revision = '216ce379d3f0'
down_revision = '2210c744e893'
branch_labels = None
depends_on = None


def upgrade():
    """Command to migrate database forward."""

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_tag_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'tag_id')
    op.add_column('tags', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tags', 'posts', ['post_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    """Command to migrate database backwards."""

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'post_id')
    op.add_column(
        'posts',
        sa.Column(
            'tag_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_tag_id_fkey', 'posts', 'tags', ['tag_id'],
                          ['id'])
    ### end Alembic commands ###
