import sqlalchemy as sa

from alembic import op

#from lib.util_datetime import tzware_datetime
#from lib.util_sqlalchemy import AwareDateTime
"""
post comments bool

Revision ID: 2feb357964a3
Revises: 813b0ce88df7
Create Date: 2016-10-09 15:52:07.545917
"""

# Revision identifiers, used by Alembic.
revision = '2feb357964a3'
down_revision = '813b0ce88df7'
branch_labels = None
depends_on = None


def upgrade():
    """Command to migrate database forward."""

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'posts', sa.Column(
            'comments_enabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    """Command to migrate database backwards."""

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'comments_enabled')
    ### end Alembic commands ###
