"""'6affe75c0cec' - Post body internal."""

import sqlalchemy as sa

from alembic import op

#from lib.util_datetime import tzware_datetime
#from lib.util_sqlalchemy import AwareDateTime
"""
Post body internal

Revision ID: 6affe75c0cec
Revises: 18248a9ed8bb
Create Date: 2016-11-17 17:14:23.045656
"""

# Revision identifiers, used by Alembic.
revision = '6affe75c0cec'
down_revision = '18248a9ed8bb'
branch_labels = None
depends_on = None


def upgrade():
    """Command to migrate database forward."""

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    """Command to migrate database backwards."""

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body')
    ### end Alembic commands ###
