import sqlalchemy as sa

from alembic import op

#from lib.util_datetime import tzware_datetime
#from lib.util_sqlalchemy import AwareDateTime
"""
blog categories

Revision ID: 813b0ce88df7
Revises:
Create Date: 2016-10-02 18:59:33.812265
"""

# Revision identifiers, used by Alembic.
revision = '813b0ce88df7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """Command to migrate database forward."""

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'categories',
        sa.Column(
            'id', sa.Integer(), nullable=False),
        sa.Column(
            'title', sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint('id'))
    op.add_column(
        'posts', sa.Column(
            'category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    """Command to migrate database backwards."""

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'category_id')
    op.drop_table('categories')
    ### end Alembic commands ###
