import sqlalchemy as sa

from alembic import op

#from lib.util_datetime import tzware_datetime
#from lib.util_sqlalchemy import AwareDateTime
"""
x

Revision ID: af9f94db37ba
Revises: 849f01f7479d
Create Date: 2016-10-09 17:56:28.196142
"""

# Revision identifiers, used by Alembic.
revision = 'af9f94db37ba'
down_revision = '849f01f7479d'
branch_labels = None
depends_on = None


def upgrade():
    """Command to migrate database forward."""

    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    """Command to migrate database backwards."""

    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
