"""'9583cbd0377a' - Page attributes."""

import sqlalchemy as sa

from alembic import op

#from lib.util_datetime import tzware_datetime
#from lib.util_sqlalchemy import AwareDateTime
"""
Page attributes

Revision ID: 9583cbd0377a
Revises: d987888a7460
Create Date: 2016-11-01 19:17:36.702853
"""

# Revision identifiers, used by Alembic.
revision = '9583cbd0377a'
down_revision = 'd987888a7460'
branch_labels = None
depends_on = None


def upgrade():
    """Command to migrate database forward."""

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'attributes',
        sa.Column(
            'id', sa.Integer(), nullable=False),
        sa.Column(
            'request', sa.Text(), nullable=False),
        sa.Column(
            'key', sa.Text(), nullable=False),
        sa.Column(
            'value', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id'))
    ### end Alembic commands ###


def downgrade():
    """Command to migrate database backwards."""

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attributes')
    ### end Alembic commands ###
