import sqlalchemy as sa

from alembic import op

from lib.util_datetime import tzware_datetime
from lib.util_sqlalchemy import AwareDateTime
from sqlalchemy.dialects import postgresql
"""
posts are a resource

Revision ID: 849f01f7479d
Revises: a3e07bfe3c3a
Create Date: 2016-10-09 17:15:21.661215
"""

# Revision identifiers, used by Alembic.
revision = '849f01f7479d'
down_revision = 'a3e07bfe3c3a'
branch_labels = None
depends_on = None


def upgrade():
    """Command to migrate database forward."""

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'posts', sa.Column(
            'created_on', AwareDateTime(), nullable=True))
    op.add_column(
        'posts', sa.Column(
            'updated_on', AwareDateTime(), nullable=True))
    op.drop_column('posts', 'last_updated')
    ### end Alembic commands ###


def downgrade():
    """Command to migrate database backwards."""

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'posts',
        sa.Column(
            'last_updated',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True))
    op.drop_column('posts', 'updated_on')
    op.drop_column('posts', 'created_on')
    ### end Alembic commands ###
