import sqlalchemy as sa

from alembic import op

from lib.util_datetime import tzware_datetime
from lib.util_sqlalchemy import AwareDateTime
"""
posts last updated

Revision ID: a3e07bfe3c3a
Revises: 2feb357964a3
Create Date: 2016-10-09 17:06:18.565068
"""

# Revision identifiers, used by Alembic.
revision = 'a3e07bfe3c3a'
down_revision = '2feb357964a3'
branch_labels = None
depends_on = None


def upgrade():
    """Command to migrate database forward."""

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'posts', sa.Column(
            'file_hash', sa.String(length=128), nullable=True))
    op.add_column(
        'posts', sa.Column(
            'last_updated', AwareDateTime(), nullable=True))
    op.add_column(
        'posts', sa.Column(
            'preview_paragraphs', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    """Command to migrate database backwards."""

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'preview_paragraphs')
    op.drop_column('posts', 'last_updated')
    op.drop_column('posts', 'file_hash')
    ### end Alembic commands ###
